version: "2"
services:
  db:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=nicolas
      - POSTGRESQL_PASSWORD=nicolas
      - POSTGRESQL_DATABASE=nicoentrega
  web:
    build: .
    volumes:
      - ./project:/project
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    working_dir: /project
    stdin_open: true
    stop_signal: SIGINT
    command: ["./wait-for-it.sh", "db:5432", "--", "mvn", "spring-boot:run"]